version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:latest
    volumes:
      - mssql_data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Express
    ports:
      - "1433:1433"

volumes:
  mssql_data: